[package]
name = "4x8matrix/windline"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["boatbomber (https://boatbomber.com)", "AsynchronousMatrix (https://www.asyncmatrix.dev/)"]

description = "A simple re-upload of the 'Windline' module found in Boatbombers windshake tech demo."

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]